name: Python CI

on:
  push:
  schedule:
    - cron: '0 2 * * *'  # UTC 時間每天 02:00 跑一次（台灣時間 +8）

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        run: python cnyes_news_scraper_final.py
